### ISSUE TITLE
Discovering identities fails if the target user has multiple claims

### ISSUE THREAD

**Issue by aryanjassal** [MatrixAI/Polykey-CLI#181]
### Describe the bug

If the user has claimed their github identity multiple times, then discovering the user fails with the following error:
`WARN:polykey.PolykeyAgent.task v0phkmdj0tlo0146ppc9ce79g0k:Failed - Reason: ErrorTaskTimeOut`

However, when I delete the second claimed gist, then the discovery command works fine once again.

### To Reproduce

1. Authenticate with Github
2. Claim identity
3. Discovery works fine
4. Claim identity again
5. Discovery fails
6. Delete gist resultant from second claiming
7. Discovery works

### Expected behavior

The discovery command should work regardless of there being multiple claims.

Should it even be possible to perform multiple claims?

### Platform (please complete the following information)

* Device: Acer Spin 3 (SP314-54N)
* OS: Arch Linux (Kernel 6.8.5-arch1-1 64-bit)
* Version: 1.2.3-alpha.4

### Additional context

> I think this can be a solution
>
> ![image](https://uploads.linear.app/e2a70dcf-d4d4-49a0-8551-1f7b7c87efa2/ff202f98-b46f-4c57-8013-f71352b4dde1/cf002437-0e39-4e2b-8b12-ac1c6d43ee3b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2UyYTcwZGNmLWQ0ZDQtNDlhMC04NTUxLTFmN2I3Yzg3ZWZhMi9mZjIwMmY5OC1iNDZmLTRjNTctODAxMy1mNzEzNTJiNGRkZTEvY2YwMDI0MzctMGUzOS00ZTJiLThiMTItYWMxYzZkNDNlZTNiIiwiaWF0IjoxNzE1NTU3NTk3LCJleHAiOjMzMjg2MTE3NTk3fQ.KMI2KyWFanzXl3U4Vix_OyjhjyxX2h76H2GdVrI-Kko)

### Notify maintainers

@tegefaulkes @amydevs

- [ ] Also notify @CryptoTotalWar once this bug is fixed so a mention can be made in the pk docs

**Comment by tegefaulkes** [comment]
How is it failing? Are you only getting that logger warning? That only means a single discovery task is failing. This is not a failure of the whole discovery process.

Were you missing any of the vertices in the gestalt after discovery? Did the process crash? What did it fail to do that it should be doing? Keep in mind, logger warnings are not explicit errors.

I need more details because right now all I can see is that you had a claim to a node that was not running and just failed to process that one node. That's not a problem in the current design.

**Comment by CMCDragonkai** [comment]
Yes only the warning appears. And then nothing happens.

The GG is not being updated for whatever reason. The discovery command completes by then doesn't do the right now.

Then vault sharing could not be achieved.

Whatever the problem is, it should result in a task timeout. However the program is running it should succeed with this process being understood:

![image](https://github.com/MatrixAI/Polykey-CLI/assets/640797/260e7bf9-0aec-4d00-b9fe-153a2ecd781e)

**Comment by CMCDragonkai** [comment]
> How is it failing? Are you only getting that logger warning? That only means a single discovery task is failing. This is not a failure of the whole discovery process.

Yes a single task timeout.

> Were you missing any of the vertices in the gestalt after discovery? Did the process crash? What did it fail to do that it should be doing? Keep in mind, logger warnings are not explicit errors.

The entire sharing the vault process could not be accomplished. Only after DELETING all claims except 1 did the sharing process complete. I believe the GG did not update at all. When listing the identities on the GG, it never showed `aryanjassal` there. Only after deleting all claims except 1, and performing discovery again, did `aryanjassal` show up on the `polykey identities list` command. That's the problem!

> I need more details because right now all I can see is that you had a claim to a node that was not running and just failed to process that one node. That's not a problem in the current design.

All nodes were running. There was only 2 nodes. My node and aryanjassal's node. And multiple claims from Aryan's node to his Github identity. The same node ID was used multiple times, there was no change over or rotation of the public key.

**Comment by CMCDragonkai** [comment]
@aryanjassal just a note your reproduction isn't the best, as this requires 2 parties to replicate. Best way to do this in the future is to just take a asciicast of the 2 parties. (You can simulate with 2 github identities).

**Comment by CMCDragonkai** [comment]
My diagram is actually important for achieving gestalt revocation (in https://github.com/MatrixAI/Polykey/issues/715) - the discovery process must be capable of using the IdPs to query things from recent to oldest (failing that, it needs to be capable of changing its mind as it discovers new information).
