### ISSUE TITLE
`identities authenticate` fails without a desktop enviroment

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#76]
### Describe the bug

Running `polykey identities authenticate` in an environment that is missing a desktop environment or a web browser fails.

I suppose this somewhat intended since the OAUTH procedure depends on a web browser. But the error throw is very low level in this case. That said I don't think we have a method of adding an identity without going through OAUTH. So how do we add identities to nodes in a server environment.

I think we can to the browser portion of the procedure on a different computer, so the only issue here is that the command is crashing while failing to spawn the browser.

### To Reproduce

1. In an enviroment that lacks the desktop such as an Ubuntu server, run the `polykey identities authenticate command` This will throw `Error: spawn xdg-open ENOENT`.

### Expected behaviour

If we fail to spawn a web browser then just proceed as normal. Don't crash the command.

### Screenshots

![image](https://github.com/MatrixAI/Polykey-CLI/assets/22425593/55a95df2-cbd0-4780-8ad6-a0a8337fcfed)

### Platform (please complete the following information)
 - Device: Ubuntu VM running in an Unraid NAS
 - OS: Ubuntu 22.04

**Comment by tegefaulkes** [comment]
I think all we really need here is better error handling for the authentication process. If we fail to open a browser, either due to the a browser is missing or even x-server is missing. we just need to ignore the problem and just print out the URL.

**Comment by CMCDragonkai** [comment]
If a browser is not available, it is not possible for one to automatically open it up.

In that case the correct procedure is to just tell the user to visit the particular URL that we would have auto opened it to.

This should be similar to the tailscale login command.

**Comment by amydevs** [comment]
I personally also think that the exec for should happen on the CLI client and not the CLI agent. This would make it so that it is the client's responsibility to engage with the OAuth flow, whilst the agent simply just passively waits for a response from the OAuth server. (In this case it's polling).

**Comment by CMCDragonkai** [comment]
Would it work whether the client is remote to the agent? I think in that case, it would need to be client opening the browser.

**Comment by amydevs** [comment]
Yes, the client would need to be the one opening the browser window. The agent currently does this, but it doesn't make sense that the agent does this currently. As it would not work if the client is remote to the agent. Furthermore, if we were to use the Polykey library directly as a client, there would be implicit behaviour that is happening when we make the `identitiesAuthenticate` RPC call.

**Comment by amydevs** [comment]
My bad, I thought I remembered it as the agent opened the browser, the client does open the browser correctly

**Comment by tegefaulkes** [comment]
Ok, so it seems that the indentitiesUtils has a `browser` function being called by the CLI. This is what handles spawing the browser. The placement seems weird that the function is defined in the `Polykey` lib but only used by the `Polykey-CLI`. It's going to make fixing it annoying too. 

So I'm just going to transplant that function into the `Polykey-CLI` utils and fix it there.

**Comment by CMCDragonkai** [comment]
Assign yourself the issues if you're working on it!

**Comment by CMCDragonkai** [comment]
Did you check this? https://github.com/MatrixAI/Polykey-CLI/issues/76#issuecomment-1853096865. If you are in a non desktop environment. You should just give the URL to the user to open up manually.

**Comment by CMCDragonkai** [comment]
Check how tailscale does it too.

**Comment by tegefaulkes** [comment]
The command already gives your the URL to go to. So all I had to ensure is that failing to open the browser doesn't cause the process to crash.

**Comment by CMCDragonkai** [comment]
Great - so in that case, the user is expected to open it up.

**Comment by CMCDragonkai** [comment]
I just had to do this for a new computer that didn't have a DE.

I noticed that indeed, we can do this with Github provider.

However... for other systems, it might be a bit more difficult. Since some OAuth flows require one to visit a long link.

Upon authenticating the long link - usually there's a redirect to the web app. However this doesn't really make sense in the context of a CLI app, thus it won't be able to redirect backwards. This is why there's an underlying polling.

But it is interesting, that if you had a single computer (and not even a mobile phone) and no DE at all, then no ability to visit the web link to authenticate, unless you had a "console browser".
